# Alembic 配置文件
# 注意: SQLAlchemy URL 不在本文件指定,改在 packages/db-migrations/env.py
# 中根据当前运行环境(开发模式 / PyInstaller 打包模式)动态生成
[alembic]
script_location = packages/db-migrations
# sqlalchemy.url 留空,env.py 会覆盖
sqlalchemy.url =

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
